### ISSUE TITLE
Analysis of the current month's tasks

### ISSUE THREAD

**Issue by manparvesh** [dude-pa/dude#4]
What should happen?
-------------------
Analysis of the current month's tasks
- What percentage of them were completed
- How frequently the entries were made, etc

Any ideas on how to implement it?
---------------------------------
- Go through all the files in the diary folder (<config-folder>/diary/) with the name that matches the current month and year, and check the completed and incomplete tasks

**Comment by rishabh3** [comment]
@manparvesh  I am new to opensource i would like to work on it please help me!

**Comment by manparvesh** [comment]
Hi @rishabh3,
Thanks for your interest in the project. You can take a look at the [Contributing guidelines](https://github.com/dude-pa/dude/blob/master/.github/CONTRIBUTING.md). In case of any doubts, you can ask me here.

**Comment by rishabh3** [comment]
Hi,
I was able to set all the packages but dude is not working it shows all the
list of commands but when i run any command it says command not found!
Please help!

**Comment by manparvesh** [comment]
How are you running a command? you need to prepend `dude` to your commands

**Comment by rishabh3** [comment]
Yeah i am prepending

**Comment by manparvesh** [comment]
Can you tell me your OS and the complete procedure you followed for this? I am not able to see anything like this in my system.

**Comment by rishabh3** [comment]
Ok so i am running ubuntu gnome 16.04
And i am using anaconda python 3.5
So i downloaded ur project unzipped it
Then i installed virtualenv and made virtual environment just as u had
mentioned.
Then i pip installed project in the environment.
And it downloaded all the dependencies for the project.
After successfully completing it when i run dude --help it gives all the
help commands and everything as shown in the code but when i run command
like dude chat hi it says no such command.
Also there was error in the vocabulary file not found error when i change
the file path and give the entire path in the code segment where we make a
dictionary for word and meaning reading it from file so there it required
some changes in my case.

**Comment by manparvesh** [comment]
Oh I am using Python 2.7. Maybe that is the problem?
Or you can try installing python-dev, maybe that can work

**Comment by manparvesh** [comment]
And regarding the vocabulary file not found, it is a bug. Referenced in #7

**Comment by rishabh3** [comment]
@manparvesh so now its working python 2.7 thanks for the help!

**Comment by rishabh3** [comment]
@manparvesh
So after successfully running ur code i saw these things
1) dude diary ct
For any task number greater than the index gave index out of bounds error.
2)also u have made a function for date
So what i have thought is to store date as a field in the task
This will help u to compare it with current month and seperate the current
month's task and after separating and storing it as list or something u can
always analyze for the percentage.
So is this what was the issue about and is my thinking correct?

**Comment by manparvesh** [comment]
Yes, you are thinking correct! You are welcome to create a PR for this.
However for the index out of bounds error, I think you should create a new Issue and we should fix it there.

**Comment by rishabh3** [comment]
No i have already fixed it so if any one will give a wrong index then it continuously ask for a valid input

**Comment by manparvesh** [comment]
I understand. I am asking you to create an Issue describing the bug and then a Pull request fixing that issue.

**Comment by rishabh3** [comment]
@manparvesh can you help me what to do now? After working on this issue what should i do? I didnot understand what you meant by pull request.

**Comment by rishabh3** [comment]
like now i have completed it and want to put my code what should i do? please tell me the steps 
First time so i have no idea about this

**Comment by manparvesh** [comment]
@rishabh3 you have made the changes in your local machine. But you need to make the changes in the github repository as well. 
- For that, you should first fork the project (third button at the top of every repository). When you do that, a copy of this repository will be made in your account. 
- Then you should clone it and make the changes in the code.
- Add and commit the changes, and then push to your repository (remember that you cannot push to this repository)
- When you push the code to your repo, a button will be displayed showing that you can create a pull request.
- Then you need to provide a description of what you have fixed.
- Then I will review the changes in the code..
- When I accept the pull request, your code will be merged in the main repo.

**Comment by rishabh3** [comment]
Thanks

**Comment by rishabh3** [comment]
@manparvesh  I have made the corresponding changes and committed it u can take a look

**Comment by manparvesh** [comment]
@rishabh3 there are bugs after merging your code. Please consider all possibilities next time
- you have written `date = entry['date']` 2 times, but there is no `'date'` key 
- you are taking all the files when analyzing and it includes notes files as well, hence there are errors in running analyze command
- You should [write good commit messages](https://github.com/erlang/otp/wiki/Writing-good-commit-messages).

**Comment by rishabh3** [comment]
@manparvesh i have made the changes mentioned by you

**Comment by rishabh3** [comment]
@manparvesh
I have made the changes for the bugs u have mentioned.

**Comment by manparvesh** [comment]
@rishabh3 The changes made in your repo can no longer be added to the PR, since the PR is already merged. I have fixed the bugs in your code, but please take care of these things next time.
Since your repo is not synced with the main repo, you can do so by taking a look [here](https://help.github.com/articles/syncing-a-fork/)
